### ISSUE TITLE
Add support for other web-drivers

### ISSUE THREAD

**Issue by vania-pooh** [kybu/headless-selenium-for-win#15]
E.g. other browsers on Windows like Chrome or Firefox can be launched like IE using driver binary. It would be great to have just an ability to specify driver binary and after starting its process simply proxy all requests to the port.

**Comment by kybu** [comment]
Sure, that's doable. Selenium driver could be specified by an environment variable. Command line parameters are forwarded to the driver.

**Comment by aandryashin** [comment]
Actually, enough to provide path to driver  as command line parameter, it can simplify search driver code.

**Comment by vania-pooh** [comment]
@kybu how could we help to provide PR for this feature? This could dramatically increase total number of use cases for your tool.

**Comment by kybu** [comment]
It is a simple change, I will get round to do it in a few days. It would help me, if you could test it though.

**Comment by kybu** [comment]
There is a release https://github.com/kybu/headless-selenium-for-win/releases/tag/v1.4.alpha1
Selenium driver executable name can be specified by `HEADLESS_DRIVER` environment variable. I haven't tested it yet, so any feedback is appreciated.

**Comment by AleksanderPopov** [comment]
@kybu thank you! I'll try to test it today and give you some feetback.

**Comment by vania-pooh** [comment]
@kybu still testing this stuff, stay tuned.

**Comment by vania-pooh** [comment]
Tested. The binary is launched but there are issue with passing arguments. On the picture I successfully start Geckodriver manually but using `headless_ie_selenium` it does not work.
![screen shot 2017-06-26 at 5 05 26 pm](https://user-images.githubusercontent.com/829320/27543063-bdd57b9e-5a91-11e7-93b8-7922782fac9f.png)

**Comment by kybu** [comment]
Thanks, I will try it when I get home. Could you meanwhile set `HEADLESS_DRIVER=geckodriver.exe` and try again? Thanks.

**Comment by vania-pooh** [comment]
Same stuff.
![screen shot 2017-06-26 at 5 14 40 pm](https://user-images.githubusercontent.com/829320/27543496-ff07c008-5a92-11e7-8b93-9aee231322ee.png)

**Comment by AleksanderPopov** [comment]
@kybu can you please confirm issue above?

**Comment by cawilliamson** [comment]
@vania-pooh Just out of curiosity - what happens if you run the following?

PATH=$PATH:/usr/lib/selenium HEADLESS_DRIVER=geckodriver.exe ./headless_ie_selenium.exe --port 4444 --host ::

I noticed you're calling the geckodriver.exe file from /usr/lib/selenium but that's not in PATH. Also a bit tricky running through Cygwin because it sets its own PATH variable and ignores the Windows one.

**Comment by vania-pooh** [comment]
@cawilliamson same result. An error above is the error from Geckodriver. That means that `headless_ie_selenium` finds Geckodriver binary.

**Comment by kybu** [comment]
Argument passing has been broken since the beginning. Only the first argument is passed on to the driver. I am looking into it.

**Comment by kybu** [comment]
There is a new release 1.4. I tested it with Firefox. Give it a try.

**Comment by vania-pooh** [comment]
Will do soon.

**Comment by vania-pooh** [comment]
I can confirm that with 1.4 it works well. Closing.
