### ISSUE TITLE
Multiple parallel headless instances to fully utilise a computer.

### ISSUE THREAD

**Issue by kybu** [kybu/headless-selenium-for-win#5]

**Comment by levsha932** [comment]
Hi kybu,
I've found your solution very useful but I'm really interesing in possiblity to run several IE's in different headless desktops so that those IE's don't interfere in tems of focus.
I have found in your code that you hardcoded the name of headless desktop so it always has the same name and so all instances of IE started in one headless desktop.
Seems it would be a good idea to generate new name of headless desktop each time. Do you have any plans on that?

**Comment by kybu** [comment]
Hi,
Yes, that's not a problem to implement.

I am actually surprised that anyone uses this little tool. I created just for fun and it has been "starred" by five people. I am always happy to hear any feedback.

**Comment by levsha932** [comment]
Acctually I've found it yesterday while looking around for the solution to run multiple IEs on one Windows without problems with focus. Seems your solution can work for that with addition of separate headless desktop for each IE.
That would be great if you can put some dynamic id in desktop naming. It's appeared to be not that easy to deal with VisualStudio with some dependencies you use (but probably I'll found somebody around to do it and pull request it then)

**Comment by kybu** [comment]
This feature has been implemented in the latest release (v1.2). Environment variable `HEADLESS_UNIQUE` has to be set in order for it to work.

**Comment by levsha932** [comment]
Thanks kybu!
For now we successfuly solve our task to run multiple isolated IEs with selenium on one win VM with desktop-utils.exe and bat files but I have to try it this way now

**Comment by clement-igonet** [comment]
So Mike, could you confirm it works as expected ?
Were you able to manage several IE instances, each one in a given virtual desktop ?

**Comment by levsha932** [comment]
@clement-igonet yes, that time we managed to create fully usable configuration and run 4 virtual desktops on one 2core VM (number of cores depends on configuration and many other things. We had 100+ such VMs that time. It's important also not to use some capabilities that make single IE to be in focus.
Strongly recommend my colleges of that time 
https://medium.com/@aandryashin/selenium-on-windows-revisited-1ab8d51ccc06
http://aerokube.com/

They not only set it up by their hands but also move forward with interesting tools

**Comment by clement-igonet** [comment]
OK, great thank for quick answer ! :-)
